### ISSUE TITLE
Extremely slow...

### ISSUE THREAD

**Issue by ryan-mccullough** [bastienperez/PowerShell-Toolbox#1]
This script takes absolutely forever to run. It takes 5-10 minutes to update each module that requires an update.

**Comment by itpro-tips** [comment]
The CMDlets provided in PowerShell (_*-Module_) are slow by default.

Update a module (with this script or even manually with default command _Update-Module_) doesn't take more than 1 or 2 minutes on my computer.
But it depends on the module (Microsoft.Graph for example takes a while to install or update, the only solution is to wait).
