### ISSUE TITLE
typo in code...trying to figure out where now

### ISSUE THREAD

**Issue by chevydust19** [bastienperez/PowerShell-Toolbox#2]
Update-EveryModule.ps1:87 char:33
+                                 | Where-Object { $_.version -ne $Gall ...
+                                 ~
An empty pipe element is not allowed.
Update-EveryModule.ps1:88 char:33
+                                 | Uninstall-Module -Force -ErrorActio ...
+                                 ~
An empty pipe element is not allowed.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : EmptyPipeElement

running powershell 5.1 
Update-EveryModule.ps1:87 char:33
+                                 | Where-Object { $_.version -ne $Gall ...
+                                 ~
An empty pipe element is not allowed.
Update-EveryModule.ps1:88 char:33
+                                 | Uninstall-Module -Force -ErrorActio ...
+                                 ~
An empty pipe element is not allowed.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : EmptyPipeElement

**Comment by itpro-tips** [comment]
Hello, 
What are the modules ?
