### ISSUE TITLE
Issue updating modules due to authenticode issue

### ISSUE THREAD

**Issue by mcdonamw** [bastienperez/PowerShell-Toolbox#3]
When running this script a number of modules error during update due to some sort of authenticode issue, requiring use of additional parameter -SkipPublisherCheck in order to update correctly.  

This seems to occur specifically with all my VMware modules.

Can the script be updated to either force this parameter or better yet prompt to proceed if it's an issue?

Error message:

------------------------------------------------------------------------------------------
VMware.VimAutomation.Core - Update from PowerShellGallery from version 12.3.0.17839688 to 12.5.0.19093566. Release date: 01/12/2022 14:18:55
PackageManagement\Install-Package : Authenticode issuer 'E=noreply@vmware.com, CN="VMware, Inc.", O="VMware, Inc.", L=Palo Alto, S=California, C=US'
of the new module 'VMware.VimAutomation.Sdk' with version '12.5.0.19093564' from root certificate authority 'CN=DigiCert Trusted Root G4,
OU=www.digicert.com, O=DigiCert Inc, C=US' is not matching with the authenticode issuer 'CN="VMware, Inc.", O="VMware, Inc.", L=Palo Alto,
S=California, C=US' of the previously-installed module 'VMware.VimAutomation.Sdk' with version '12.2.0.17531155' from root certificate authority
'CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network,
O="VeriSign, Inc.", C=US'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.4\PSModule.psm1:13067 char:20
+ ...           $sid = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : AuthenticodeIssuerMismatch,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.Install
   Package

**Comment by itpro-tips** [comment]
Hello,

I need to find a way to identify such modules and bypass the certificate.

**Comment by bastienperez** [comment]
Fix in the last release. you can use _-SkipPublisherCheck_ when you run the script
