### ISSUE TITLE
Version check wrong

### ISSUE THREAD

**Issue by trchosen1** [bastienperez/PowerShell-Toolbox#4]
Seems like the logic to detect newer versions is not accurate.

Here is an example:
CloudConnect - Update from PowerShellGallery from version 1.1.2 to 0.5.0. Release date: 05/08/2019 16:18:05

Clearly 1.1.2 is newer than 0.5.0

**Comment by bastienperez** [comment]
Hello,
The script didn't check the version itself but against the PowerShell Gallery only (but I could add this).
I just updated the script to compare the version.

**Comment by JamesGMorrison** [comment]
Hi Bastien,
Great script - very handy. Thank You.

I fixed the version checking issue by changing line 77 to
`elseif([version]$currentVersion -gt [version]$moduleInfos.Version){`

From https://invoke-thebrain.com/2018/12/comparing-version-numbers-powershell/
